on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build mvn
        run: |
          .\mvnw.cmd clean package -DskipTests

      - name: Build and tag Docker image
        run: |
          docker build -t department-service:v1 .


  deploy:
    env:
      APP_PORT: ${{ secrets.APP_PORT }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    runs-on: [self-hosted]
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop and Remove Existing Containers
        continue-on-error: true
        run: docker compose down

      - name: Run with Docker Compose
        run: docker compose up -d
